--本体关节名称
roboJointNames={"world_joint",
            "shoulder_pan_joint",
            "shoulder_lift_joint",
            "elbow_joint",
            "wrist_1_joint",
            "wrist_2_joint",
            "wrist_3_joint"}
--本体连杆名称(含底座)
roboLinkNames={"base_link",
            "shoulder_link",
            "upper_arm_link",
            "forearm_link",
            "wrist_1_link",
            "wrist_2_link",
            "wrist_3_link"}

--机械手连杆名称
handLinkNames={"bh_base_link",
"bh_finger_11_link",
"bh_finger_12_link",
"bh_finger_13_link",
"bh_finger_21_link",
"bh_finger_22_link",
"bh_finger_23_link",
"bh_finger_31_link",
"bh_finger_32_link",
"bh_finger_33_link",
}

--8自由度机械手关节名称
handJointNames={
    "bh_base_joint",
    "bh_j11_joint",
    "bh_j12_joint",
    "bh_j13_joint",
    "bh_j21_joint",
    "bh_j22_joint",
    "bh_j23_joint",
    "bh_j31_joint",
    "bh_j32_joint",
    "bh_j33_joint"
}